Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  
  config.vm.network "private_network", ip: "192.168.56.80"
  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "5120"  # 5GB
    vb.cpus = 4
  end

  config.vm.provision "shell", path: "provisioning/setup-wordpress.sh"
end