Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    config.vm.network "private_network", ip: "192.168.56.17"
    config.vm.network "public_network"

    config.vm.synced_folder "./scripts", "/opt/scripts"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 3072
        vb.cpus = 4
    end
end